spring:
  application:
    name: Parking Lot BE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: parkinglotdb
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /